# Site settings
title: efpasia
description: >-
  thinking about something
baseurl: ""
url: "https://efpasia.github.io"

author:
  text me if you want
  efpasia@gmail.com


twitter_username: geneilliss
github_username: efpasia
linkedin_username: germi

theme: minima

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

header_pages:
  - about.md
  - blog/index.md

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "efpasia"
